
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Tests
        working-directory: ./backend
        run: npm test

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Authenticate with Google Cloud
        run: |
          echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
          gcloud config set project chronos-sa

      - name: Deploy Backend
        run: |
          gcloud compute instances update-container instance-20250225-125631 \
            --zone=africa-south1-a \
            --container-image="africa-south1-docker.pkg.dev/chronos-sa/chronos-backend/chronos-backend:latest"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
       
      - name: Fix React-Scripts Permissions
      working-directory: ./frontend
      run: chmod +x ./node_modules/.bin/react-scripts

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
